gitlab:
  user_initpassword: "password1234"
  accesstoken: "bfSA7xtqH-1ErYuF8HCW" 
  gitlabDomain: "https://gitlab.choilab.xyz/api/v4/"
  gitlabHost: "https://gitlab.choilab.xyz/"

  group_member_default_expires: "2022-01-01"

  # app template gitlab project ID
  root_appId:
    python: 1
    springboot: 2
    appofapps: ''
  
jenkins:
  access_token: "11e6eff1ef8d94d41d94f7cdf4e2c73a8b"
  host: "https://jenkins.choilab.xyz/"
  admin_user: "admin"

  createjob:
    job_template: "job_templatev1.xml"
    
helm:
  root_Id:
    springboot: 10
  
  common_helm_groupId: 33
  default_resources:
    cpu: "0.5"
    memeory: "512Mi"

  springboot:
    app_gitlab_projectid: 10
    helm_gitlab_groupurl: "common/common-helm"
    helm_gitlab_projectname: "springboot-helm"

argocd:
  access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiMmZkYjcxNS1kZmRkLTQwOTgtYjk0Yy1lMDIyZTBkYTAxM2IiLCJpYXQiOjE2MjM4NDcwMTMsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTYyMzg0NzAxMywic3ViIjoiY2hvaTphcGlLZXkifQ.k8K8-nsyv-oXhLu9EQQkb5XiX0jEk9hDAJL_PRmZ3YQ"
  host: "https://argocd.choilab.xyz/"
  admin_user: "choi"
  git_repo:
    app:
      name: "app_appofapps"
      id: 17 # appofpass gitlab project ID
      group_name: "common/argocd"
    remote_url: "https://gitlab.choilab.xyz/common/argocd/app_appofapps.git"
  
  templates:
    values_each_template_path: "argocd_appofapps_valueseach_template.yaml"
    values_template_path: "argocd_appofapps_values.yaml"

docker:
  prviate_registry_host: "docker.choilab.xyz"
  protocol: "https"