gitlab:
  user_initpassword: "password1234"
  accesstoken: "bfSA7xtqH-1ErYuF8HCW" 
  gitlabDomain: "https://gitlab.choilab.xyz/api/v4/"

  group_member_default_expires: "2022-01-01"

  root_appId:
    python: 1
    springboot: 2
    appofapps: ''
  
jenkins:
  access_token: "11e6eff1ef8d94d41d94f7cdf4e2c73a8b"
  host: "https://jenkins.choilab.xyz/"
  admin_user: "admin"

  createjob:
    job_template: "job_templatev1.xml"
    
helm:
  root_Id:
    springboot: 10
  
  common_helm_groupId: 33
  default_resources:
    cpu: "0.5"
    memeory: "512Mi"

argocd:
  access_token: ""
  host: "https://argocd.choilab.xyz/"
  admin_user: "choi"